export default {
  addToHomeScreen: {
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    fontFamily: '"Miriam", Monaco, monospace',
  },
  background: {
    backgroundColor: "black",
    borderRadius: "6px",
    height: "25px",
    margin: "10px",
    width: "25px",
  },
  contentAdd: {
    color: "white",
    height: "15px",
    marginLeft: "5px",
    marginTop: "5px",
    width: "15px",
  },
  exitToApp: {
    height: "25px",
    marginBottom: "5px",
    marginLeft: "10px",
    transform: "rotate(-90deg)",
    width: "25px",
  },
  flexColumn: {
    backgroundColor: "rgb(37, 55, 72)",
    display: "flex",
    flexDirection: "column",
    minHeight: "100vh",
    paddingLeft: "25px",
    paddingRight: "25px",
    flexBasis: "100%",
  },
  header: {
    color: "#b7d0e8",
    fontFamily: '"Miriam", Monaco, monospace',
    fontWeight: 400,
  },
  imperative: {
    color: "#666666",
    fontFamily: '"Miriam", Monaco, monospace',
    fontSize: "1.25rem",
    fontSize: "20px",
    fontWeight: 700,
    marginBottom: ".35em",
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflow: "hidden",
    padding: 0,
    textAlign: "left",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  instruction: {
    alignItems: "center",
    backgroundColor: "#fffaef",
    borderRadius: "10px",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    paddingBottom: "15px",
    paddingLeft: "25vw",
    paddingRight: "25vw",
    paddingTop: "15px",
  },
  small: {
    fontSize: "x-small"
  },
  subText: {
    color: "#b7d0e8",
    fontFamily: '"Miriam", Monaco, monospace',
    fontWeight: 400,
    marginBottom: "1.08696%",
    textAlign: "center",
  },
}
